name: Run speedlify

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * 2"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout results
        id: checkout-results
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: refs/heads/main
          path: results
      - name: Checkout speedlify
        uses: actions/checkout@v4
        with:
          path: default
      - name: Copy existing results
        if: steps.checkout-results.outcome == 'success'
        run: cp -r results/_data/results/ default/_data/results
      - name: Install npm dependencies
        run: npm install
        working-directory: default
      - name: Run test-pages
        run: npm run test-pages
        working-directory: default
      - name: Check for Lighthouse Regressions
        id: check_regressions
        run: |
          node default/check-lighthouse-regressions.js results/results-last-runs.json default/_data/results-last-runs.json
        env:
          REGRESSION_THRESHOLD_PERCENT: 10 # Default threshold for regression
      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: default/_data/results
      - name: Upload results-last-runs artifact
        uses: actions/upload-artifact@v4
        with:
          name: results-last-runs.json
          path: default/_data/results-last-runs.json
      - name: Push results to main branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          cd results
          
          cp -r ../default/_data/results/* _data/results/
          cp ../default/_data/results-last-runs.json _data/results-last-runs.json
          
          if [ -f ../default/_data/lighthouse-metrics.csv ]; then
            cp ../default/_data/lighthouse-metrics.csv _data/lighthouse-metrics.csv
          fi
          
          echo "Files to be committed:"
          git status --porcelain
          
          git add _data/
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            echo "Committing changes..."
            git commit -m "Update Speedlify results and metrics CSV"
            git push origin main
          fi
      
  # Separate job for building and deploying to GitHub Pages
  build-and-deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4