name: Run speedlify

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout results
        id: checkout-results
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: refs/heads/main
          path: results
      - name: Checkout speedlify
        uses: actions/checkout@v2
        with:
          path: default
      - name: Copy existing results
        if: steps.checkout-results.outcome == 'success'
        run: cp -r results/. default/_data
      - name: Install npm dependencies
        run: npm install
        working-directory: default
      - name: Run test-pages
        run: npm run test-pages
        working-directory: default
      - name: Check for Lighthouse Regressions
        id: check_regressions
        run: |
          node default/check-lighthouse-regressions.js results/results-last-runs.json default/_data/results-last-runs.json
        env:
          REGRESSION_THRESHOLD_PERCENT: 10 # Default threshold for regression
      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: default/_data/results
      - name: Upload results-last-runs artifact
        uses: actions/upload-artifact@v4
        with:
          name: results-last-runs.json
          path: default/_data/results-last-runs.json
      - name: Push results to main branch
        run: |
          # Copy results to a temporary directory
          mkdir -p temp_results
          cp -r default/_data/* temp_results/
          
          # Configure git
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # Clone the repository again (to main branch)
          git clone --single-branch --branch main https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main_repo
          
          # Copy results to the main branch repository
          cp -r temp_results/* main_repo/
          
          # Commit and push changes
          cd main_repo
          git add .
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Speedlify results"
            git push origin main
          fi